services:
    postgresql:
            container_name: docker_tp2_sql
            image: postgres:latest
            environment:
              POSTGRES_USERNAME: postgres
              POSTGRES_PASSWORD: postgres
              POSTGRES_DB: db_tp2_relacionamentos_sql
            ports:
              - "5432:5432"
            volumes:
              - tp2_data:/var/lib/postgresql/data

volumes:
    tp2_data: